#!/bin/bash
stow -S zsh vim tmux

if [ ! -f ~/.vim/autoload/plug.vim ]; then
  echo Installing vim-plug...
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

curl -sL zplug.sh/installer | zsh

tic tmux-terminfo

